CREATE DATABASE IF NOT EXISTS ptero_web CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ptero_web;

CREATE TABLE users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE servers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL,
  ptero_id INT UNSIGNED DEFAULT 0,
  identifier VARCHAR(100) DEFAULT '',
  memory INT UNSIGNED NOT NULL,
  disk INT UNSIGNED NOT NULL,
  cpu INT UNSIGNED NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_servers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
